# fly.toml app configuration file generated for phonebook-fullstackopen-hoanghiep on 2025-02-20T10:32:03+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonebook-fullstackopen-hoanghiep'
primary_region = 'sin'

[build]

[env]
  PORT = "3001" # add this
  MONGODB_URI="mongodb+srv://hunghiephainhuan1412:Hunghiephainhuan1412@cluster0.g3yh9.mongodb.net/phonebook?retryWrites=true&w=majority&appName=Cluster0"
  MONGODB_URI_PASSWORD="Hunghiephainhuan1412"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
